version: '3.8'

services:
  test-runner:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    volumes:
      - .:/app
      - test-results:/app/test-results
    environment:
      - PYTHONPATH=/app
      - PYTEST_HEADLESS=true
    command: python tests/run_tests.py quick

  full-test-suite:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    volumes:
      - .:/app
      - test-results:/app/test-results
    environment:
      - PYTHONPATH=/app
      - PYTEST_HEADLESS=true
    command: python tests/run_tests.py all
    
  api-tests:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    volumes:
      - .:/app
      - test-results:/app/test-results
    environment:
      - PYTHONPATH=/app
    command: python tests/run_tests.py api
    
  frontend-tests:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    volumes:
      - .:/app
      - test-results:/app/test-results
    environment:
      - PYTHONPATH=/app
      - PYTEST_HEADLESS=true
    command: python tests/run_tests.py frontend
    
  performance-tests:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    volumes:
      - .:/app
      - test-results:/app/test-results
    environment:
      - PYTHONPATH=/app
    command: python tests/run_tests.py performance

volumes:
  test-results: